src/main/java/br/uece/favet/model/Usuario.java
package br.uece.favet.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import br.uece.favet.model.enums.TipoGrupoUsuario;

@Entity
@Table(name = "usuario")
public class Usuario implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY, generator="usuario_id_seq")
    @SequenceGenerator(name="usuario_id_seq", sequenceName="usuario_id_seq", allocationSize=1)	
	private Long id;
	// @NotBlank
	@Column(nullable = false, length = 80)	
	private String nome;

	@Column(length = 20)	
	private String login;
	
	@Column(nullable = false, unique = true, length = 100)	
	private String email;
	@Column(nullable = false, length = 50)	
	private String senha;

	@Transient
	private String senhaConfirmacao;
	
	@OneToOne
	@JoinColumn(name = "veterinario_id", nullable=true, foreignKey = @ForeignKey(name = "fk_usuario__veterinario__veterinario_id"))	
	private Veterinario veterinario;

	@ManyToOne
	@JoinColumn(name = "grupo_id", nullable=false, foreignKey = @ForeignKey(name = "fk_usuario__grupo__grupo_id"))	
	private Grupo grupo;

	@Column(nullable=true)
	private Boolean redefinir = false;
	
	@Column(nullable=true)
	private Boolean ativo = true;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_hora_alteracao")	
	private Date dataHoraAlteracao;

	@Column(name="pode_iniciar_atendimento", nullable=true)
	private Boolean podeIniciarAtendimento = false;	
	
	public boolean validaSenha(){
		 return this.senha.equals(this.senhaConfirmacao);
	}

	@Transient
	public String getStatus(){
		return this.ativo ? "Atvo" : "Inativo";
	}
	
	@Transient
	public boolean isNaoEhVeterinario(){
		return this.grupo.getTipoGrupoUsuario() != TipoGrupoUsuario.VETERINARIO;
	}	
	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getLogin() {
		return login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getSenha() {
		return senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	public String getSenhaConfirmacao() {
		return senhaConfirmacao;
	}

	public void setSenhaConfirmacao(String senhaConfirmacao) {
		this.senhaConfirmacao = senhaConfirmacao;
	}

	public Veterinario getVeterinario() {
		return veterinario;
	}

	public void setVeterinario(Veterinario veterinario) {
		this.veterinario = veterinario;
	}

	public Grupo getGrupo() {
		return grupo;
	}

	public void setGrupo(Grupo grupo) {
		this.grupo = grupo;
	}
	
	public Boolean getRedefinir() {
		return redefinir;
	}

	public void setRedefinir(Boolean redefinir) {
		this.redefinir = redefinir;
	}

	public Boolean getAtivo() {
		return ativo;
	}

	public void setAtivo(Boolean ativo) {
		this.ativo = ativo;
	}

	public Date getDataHoraAlteracao() {
		return dataHoraAlteracao;
	}

	public void setDataHoraAlteracao(Date dataHoraAlteracao) {
		this.dataHoraAlteracao = dataHoraAlteracao;
	}

	public Boolean getPodeIniciarAtendimento() {
		return podeIniciarAtendimento;
	}

	public void setPodeIniciarAtendimento(Boolean podeIniciarAtendimento) {
		this.podeIniciarAtendimento = podeIniciarAtendimento;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((ativo == null) ? 0 : ativo.hashCode());
		result = prime
				* result
				+ ((dataHoraAlteracao == null) ? 0 : dataHoraAlteracao
						.hashCode());
		result = prime * result + ((email == null) ? 0 : email.hashCode());
		result = prime * result + ((grupo == null) ? 0 : grupo.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((login == null) ? 0 : login.hashCode());
		result = prime * result + ((nome == null) ? 0 : nome.hashCode());
		result = prime
				* result
				+ ((podeIniciarAtendimento == null) ? 0
						: podeIniciarAtendimento.hashCode());
		result = prime * result
				+ ((redefinir == null) ? 0 : redefinir.hashCode());
		result = prime * result + ((senha == null) ? 0 : senha.hashCode());
		result = prime
				* result
				+ ((senhaConfirmacao == null) ? 0 : senhaConfirmacao.hashCode());
		result = prime * result
				+ ((veterinario == null) ? 0 : veterinario.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Usuario other = (Usuario) obj;
		if (ativo == null) {
			if (other.ativo != null)
				return false;
		} else if (!ativo.equals(other.ativo))
			return false;
		if (dataHoraAlteracao == null) {
			if (other.dataHoraAlteracao != null)
				return false;
		} else if (!dataHoraAlteracao.equals(other.dataHoraAlteracao))
			return false;
		if (email == null) {
			if (other.email != null)
				return false;
		} else if (!email.equals(other.email))
			return false;
		if (grupo == null) {
			if (other.grupo != null)
				return false;
		} else if (!grupo.equals(other.grupo))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (login == null) {
			if (other.login != null)
				return false;
		} else if (!login.equals(other.login))
			return false;
		if (nome == null) {
			if (other.nome != null)
				return false;
		} else if (!nome.equals(other.nome))
			return false;
		if (podeIniciarAtendimento == null) {
			if (other.podeIniciarAtendimento != null)
				return false;
		} else if (!podeIniciarAtendimento.equals(other.podeIniciarAtendimento))
			return false;
		if (redefinir == null) {
			if (other.redefinir != null)
				return false;
		} else if (!redefinir.equals(other.redefinir))
			return false;
		if (senha == null) {
			if (other.senha != null)
				return false;
		} else if (!senha.equals(other.senha))
			return false;
		if (senhaConfirmacao == null) {
			if (other.senhaConfirmacao != null)
				return false;
		} else if (!senhaConfirmacao.equals(other.senhaConfirmacao))
			return false;
		if (veterinario == null) {
			if (other.veterinario != null)
				return false;
		} else if (!veterinario.equals(other.veterinario))
			return false;
		return true;
	}

}

src/main/java/br/uece/favet/controller/AutenticadorBean.java
package br.uece.favet.controller;

import java.io.Serializable;

import javax.enterprise.context.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import br.uece.favet.model.Consultorio;
import br.uece.favet.model.Usuario;
import br.uece.favet.model.enums.TipoGrupoUsuario;
import br.uece.favet.repository.UsuarioRepository;
import br.uece.favet.util.jsf.FacesUtil;
import br.uece.favet.util.jsf.SessionUtil;

@Named
@SessionScoped
public class AutenticadorBean implements Serializable {

	private static final long serialVersionUID = 1L;

	@Inject
	private UsuarioRepository usuarioRepository;

	private String email;
	private String senha;
	private TipoGrupoUsuario tipoGrupoUsuario;
	private Consultorio consultorio;

	public String autentica() {

		Usuario usu = usuarioRepository.porEmailSenha(this.email, this.senha);
		
		if (usu != null) {
			SessionUtil.setParam("USUARIOLogado", usu);
			this.tipoGrupoUsuario = usu.getGrupo().getTipoGrupoUsuario();
			
			return "/Home.xhtml?faces-redirect=true";
		} else {
			SessionUtil.remove("USUARIOLogado");
			FacesUtil.addErrorMessage("Usuário ou senha informado inválido.");
			return null;
		}
	}

	public String registraSaida() {

		// REMOVER USUARIO DA SESSION
		SessionUtil.remove("USUARIOLogado");

		FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
		
		this.email = null;
		this.senha = null;
		this.tipoGrupoUsuario = null;
		this.consultorio = null;

		return "/Login?faces-redirect=true";
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getSenha() {
		return senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	public TipoGrupoUsuario getTipoGrupoUsuario() {
		return tipoGrupoUsuario;
	}
	
	public boolean isAdministrador(){
		return tipoGrupoUsuario.equals(TipoGrupoUsuario.ADMINISTRADOR);
	}

	public String getNomeConsultorioDaSessao() {
		String nome = null;
		if (this.consultorio != null){
			nome = "[no "+consultorio.getNome()+"]"; 
		}
		return nome;
	}
	
	public Consultorio getConsultorio() {
		return consultorio;
	}

	public void setConsultorio(Consultorio consultorio) {
		this.consultorio = consultorio;
	}
	
}

src/main/webapp/WEB-INF/template/LayoutPadrao.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

<!-- Namespaces antes do JSF 2.2 - https://clairtonluz.github.io/blog/2014/03/2014032299.html 
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
 -->
 
<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title><ui:insert name="titulo">Sistema de Gestão Favet</ui:insert></title>
	<h:outputStylesheet library="css" name="sistema.css" />
</h:head>

<h:body>

	<p:ajaxStatus styleClass="ajax-status">
		<f:facet name="start">
			<h:graphicImage library="images" name="loading.gif" />
		</f:facet>
		<f:facet name="complete">
			<h:outputText value="" />
		</f:facet>
	</p:ajaxStatus>

	<header> 

	<div style="float: left">
		<h:link outcome="/Home">
		 <!-- 	<h:graphicImage library="images" name="ilovefavetblue.png" />  -->
		   <h:graphicImage library="images" name="logohospital2.jpg" />
		</h:link>
	</div>

	<h:link outcome="/Home">
	<div style="float: left; font-size: 20px; height: 30px; line-height: 30px; margin-left: 20px; font-weight: bold; color:#ffffff"> 
	         Hospital Veterinário HVSBC </div>
   </h:link>

	<div style="float: right; margin-right: 110px">
		<span
			style="float: left; height: 30px; line-height: 30px; margin-right: 60px; color:#ffffff">
			Olá #{seguranca.nomeUsuario}!   #{autenticadorBean.nomeConsultorioDaSessao} </span>

		<h:form style="display: inline-block">
			<p:menubar styleClass="menu-sistema">
				<p:submenu label="Cadastros" >
					<p:menuitem value="Produtos" rendered="false" />
					<p:menuitem value="Pesquisa Produtos" rendered="false"/>
					
					<p:separator />
					<p:menuitem value="Proprietários e Animais" 
						outcome="/proprietarios/Proprietarios" />
					<p:menuitem value="Pesquisa Animais" 
						outcome="/proprietarios/PesquisaProprietarios" />
						
					<p:menuitem value="Pesquisa Proprietários" 
						outcome="/proprietarios/PesquisaProprietariosSemAnimais" />					

                   <p:separator/>
                   
                   <p:menuitem value="Espécies" 
						outcome="/especies/Especies" />
					
					<p:menuitem value="Pesquisa Espécies" 
						outcome="/especies/PesquisaEspecies" />

                   <p:separator/>
                   
                   <p:menuitem value="Raças" 
						outcome="/racas/Racas" />
					
					<p:menuitem value="Pesquisa Raças" 
						outcome="/racas/PesquisaRacas" />

                   <p:separator/>
                   
                   <p:menuitem value="Veterinários" 
						outcome="/veterinarios/Veterinarios" />
					
					<p:menuitem value="Pesquisa Veterinários" 
						outcome="/veterinarios/PesquisaVeterinarios" />
											
				</p:submenu>
				
				<p:submenu label="Administração" rendered="#{autenticadorBean.administrador}">
					<p:menuitem value="Usuários" 
						outcome="/usuarios/Usuarios" />

					<p:menuitem value="Pesquisa Usuários" 
						outcome="/usuarios/PesquisaUsuarios" />
						
				</p:submenu>
				
				<p:submenu label="Operações Estoque" rendered="false">
					<p:menuitem value="Entrada de Mercadorias"
						outcome="/entradas/EntradaMercadorias" />
					<p:menuitem value="Pesquisa Entrada de Mercadorias"
						outcome="/entradas/PesquisaEntradaMercadorias" />
                    <p:separator />												
		
					<p:menuitem value="Manutenção de Estoque"
						outcome="/manutencoes/ManutencaoEstoques" />
					<p:menuitem value="Pesquisa Manutenção de Estoque"
						outcome="/manutencoes/PesquisaManutencaoEstoques" />

                    <p:separator />

					<p:menuitem value="Transferências"
						outcome="/transferencias/Transferencias" />
					<p:menuitem value="Pesquisa Transferências"
						outcome="/transferencias/PesquisaTransferencias" />
						
                    <p:separator />
				</p:submenu>

				<p:submenu label="Atendimentos">

					<p:menuitem value="Pesquisa Atendimentos (Geral)" 
					outcome="/atendimentospacientes/PesquisaAtendimentoPacientes" />

					<p:menuitem value="Lista de Espera (Exame)"
					rendered="#{seguranca.veterinarioUsuario.fazExames or seguranca.usuario.naoEhVeterinario}" 
					outcome="/atendimentospacientes/PesquisaListaEspera.xhtml?tipoatendimento=ultrassom" />

					<p:menuitem value="Lista de Espera (Cirúrgico)"
					rendered="#{seguranca.veterinarioUsuario.cirurgiao or seguranca.usuario.naoEhVeterinario}" 
					outcome="/atendimentospacientes/PesquisaListaEspera.xhtml?tipoatendimento=cirurgico" />
					
					<p:menuitem value="Lista de Espera (Clínico)" 
					rendered="#{seguranca.veterinarioUsuario.clinico or seguranca.usuario.naoEhVeterinario}"					
					outcome="/atendimentospacientes/PesquisaListaEspera.xhtml?tipoatendimento=clinico" />
					
					<p:menuitem value="Atendimento Farmácia" rendered="false"
						outcome="/atendimentos/AtendimentoMedicamentos" />
					<p:menuitem value="Pesquisa Atendimento de Medicamentos" rendered="false"
  					    outcome="/atendimentos/PesquisaAtendimentoMedicamentos" />
  					
				</p:submenu>
				<p:menuitem value="Sair" action="#{autenticadorBean.registraSaida}" />
			</p:menubar>
		</h:form>
	</div>
	<div style="clear: both"></div>
	</header>

	<div id="conteudo">
		<ui:insert name="corpo"></ui:insert>
	</div>

	<p:separator style="margin-top: 20px" />
	<footer> Faculdade de Veterinária - Favet - <a
		href="http://www.uece.br/favet/" target="_blank">www.uece.br/favet/</a>
	</footer>

</h:body>


</html>