src/main/java/br/uece/favet/model/Usuario.java
package br.uece.favet.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import br.uece.favet.model.enums.TipoGrupoUsuario;

@Entity
@Table(name = "usuario")
public class Usuario implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY, generator="usuario_id_seq")
    @SequenceGenerator(name="usuario_id_seq", sequenceName="usuario_id_seq", allocationSize=1)	
	private Long id;
	// @NotBlank
	@Column(nullable = false, length = 80)	
	private String nome;

	@Column(length = 20)	
	private String login;
	
	@Column(nullable = false, unique = true, length = 100)	
	private String email;
	@Column(nullable = false, length = 50)	
	private String senha;

	@Transient
	private String senhaConfirmacao;
	
	@OneToOne
	@JoinColumn(name = "veterinario_id", nullable=true, foreignKey = @ForeignKey(name = "fk_usuario__veterinario__veterinario_id"))	
	private Veterinario veterinario;

	@ManyToOne
	@JoinColumn(name = "grupo_id", nullable=false, foreignKey = @ForeignKey(name = "fk_usuario__grupo__grupo_id"))	
	private Grupo grupo;

	@Column(nullable=true)
	private Boolean redefinir = false;
	
	@Column(nullable=true)
	private Boolean ativo = true;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_hora_alteracao")	
	private Date dataHoraAlteracao;

	@Column(name="pode_iniciar_atendimento", nullable=true)
	private Boolean podeIniciarAtendimento = false;	
	
	public boolean validaSenha(){
		 return this.senha.equals(this.senhaConfirmacao);
	}

	@Transient
	public String getStatus(){
		return this.ativo ? "Atvo" : "Inativo";
	}
	
	@Transient
	public boolean isNaoEhVeterinario(){
		return this.grupo.getTipoGrupoUsuario() != TipoGrupoUsuario.VETERINARIO;
	}	
	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getLogin() {
		return login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getSenha() {
		return senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	public String getSenhaConfirmacao() {
		return senhaConfirmacao;
	}

	public void setSenhaConfirmacao(String senhaConfirmacao) {
		this.senhaConfirmacao = senhaConfirmacao;
	}

	public Veterinario getVeterinario() {
		return veterinario;
	}

	public void setVeterinario(Veterinario veterinario) {
		this.veterinario = veterinario;
	}

	public Grupo getGrupo() {
		return grupo;
	}

	public void setGrupo(Grupo grupo) {
		this.grupo = grupo;
	}
	
	public Boolean getRedefinir() {
		return redefinir;
	}

	public void setRedefinir(Boolean redefinir) {
		this.redefinir = redefinir;
	}

	public Boolean getAtivo() {
		return ativo;
	}

	public void setAtivo(Boolean ativo) {
		this.ativo = ativo;
	}

	public Date getDataHoraAlteracao() {
		return dataHoraAlteracao;
	}

	public void setDataHoraAlteracao(Date dataHoraAlteracao) {
		this.dataHoraAlteracao = dataHoraAlteracao;
	}

	public Boolean getPodeIniciarAtendimento() {
		return podeIniciarAtendimento;
	}

	public void setPodeIniciarAtendimento(Boolean podeIniciarAtendimento) {
		this.podeIniciarAtendimento = podeIniciarAtendimento;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((ativo == null) ? 0 : ativo.hashCode());
		result = prime
				* result
				+ ((dataHoraAlteracao == null) ? 0 : dataHoraAlteracao
						.hashCode());
		result = prime * result + ((email == null) ? 0 : email.hashCode());
		result = prime * result + ((grupo == null) ? 0 : grupo.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((login == null) ? 0 : login.hashCode());
		result = prime * result + ((nome == null) ? 0 : nome.hashCode());
		result = prime
				* result
				+ ((podeIniciarAtendimento == null) ? 0
						: podeIniciarAtendimento.hashCode());
		result = prime * result
				+ ((redefinir == null) ? 0 : redefinir.hashCode());
		result = prime * result + ((senha == null) ? 0 : senha.hashCode());
		result = prime
				* result
				+ ((senhaConfirmacao == null) ? 0 : senhaConfirmacao.hashCode());
		result = prime * result
				+ ((veterinario == null) ? 0 : veterinario.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Usuario other = (Usuario) obj;
		if (ativo == null) {
			if (other.ativo != null)
				return false;
		} else if (!ativo.equals(other.ativo))
			return false;
		if (dataHoraAlteracao == null) {
			if (other.dataHoraAlteracao != null)
				return false;
		} else if (!dataHoraAlteracao.equals(other.dataHoraAlteracao))
			return false;
		if (email == null) {
			if (other.email != null)
				return false;
		} else if (!email.equals(other.email))
			return false;
		if (grupo == null) {
			if (other.grupo != null)
				return false;
		} else if (!grupo.equals(other.grupo))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (login == null) {
			if (other.login != null)
				return false;
		} else if (!login.equals(other.login))
			return false;
		if (nome == null) {
			if (other.nome != null)
				return false;
		} else if (!nome.equals(other.nome))
			return false;
		if (podeIniciarAtendimento == null) {
			if (other.podeIniciarAtendimento != null)
				return false;
		} else if (!podeIniciarAtendimento.equals(other.podeIniciarAtendimento))
			return false;
		if (redefinir == null) {
			if (other.redefinir != null)
				return false;
		} else if (!redefinir.equals(other.redefinir))
			return false;
		if (senha == null) {
			if (other.senha != null)
				return false;
		} else if (!senha.equals(other.senha))
			return false;
		if (senhaConfirmacao == null) {
			if (other.senhaConfirmacao != null)
				return false;
		} else if (!senhaConfirmacao.equals(other.senhaConfirmacao))
			return false;
		if (veterinario == null) {
			if (other.veterinario != null)
				return false;
		} else if (!veterinario.equals(other.veterinario))
			return false;
		return true;
	}

}

src/main/java/br/uece/favet/controller/CadastroRacaBean.java
package br.uece.favet.controller;

import java.io.Serializable;
import java.util.List;

import javax.faces.bean.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import br.uece.favet.model.Especie;
import br.uece.favet.model.Raca;
import br.uece.favet.model.enums.TipoPorte;
import br.uece.favet.repository.EspecieRepository;
import br.uece.favet.service.CadastroRacaService;
import br.uece.favet.service.NegocioException;
import br.uece.favet.util.jsf.FacesUtil;

@Named
@ViewScoped
public class CadastroRacaBean implements Serializable {

	private static final long serialVersionUID = 1L;

	private Raca raca;
	private List<Especie> especies;
	
	@Inject
	private CadastroRacaService cadastroRacaService;
	
	@Inject
	private EspecieRepository especieRepository;	
	
	public Raca getRaca() {
		return raca;
	}

	public void setRaca(Raca raca) {
		this.raca = raca;
	}

	public List<Especie> getEspecies() {
		return especies;
	}

	public TipoPorte[] getTipoPorte(){
	     return TipoPorte.values();
	}	
	
	
	public CadastroRacaBean() {
        limpar();
	}

	public void limpar() {
		raca = new Raca();
	}

	public void salvar() {

		try {

	    	this.raca = this.cadastroRacaService
							.salvar(this.raca);
		    	
			FacesUtil.addInfoMessage("Raça salva com sucesso!");

		} catch (NegocioException ne) {
			FacesUtil.addErrorMessage("Erro ao Salvar Raça 1: "+ne.getMessage());
		} 	catch (Exception e){
			FacesUtil.addErrorMessage("Erro ao Salvar Raça 2: "+e.getMessage()+", Causa :"+e.getCause());
		} 
		
	}
	
	public void inicializar() {
		if (FacesUtil.isNotPostback()) {
			this.especies = this.especieRepository.especies();			
		}
	}
	
	public boolean isEditando() {
		return this.raca.getId() != null;
	}
	
}

src/main/java/br/uece/favet/controller/PesquisaUsuarioBean.java
package br.uece.favet.controller;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.faces.bean.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import br.uece.favet.model.Usuario;
import br.uece.favet.repository.UsuarioRepository;
import br.uece.favet.repository.filter.UsuarioFilter;

@Named
@ViewScoped
public class PesquisaUsuarioBean implements Serializable {

	private static final long serialVersionUID = 1L;

	@Inject
	private UsuarioRepository usuarioRepository;

	private UsuarioFilter filtro;

	private Set<Usuario> usuariosFiltrados;

	public PesquisaUsuarioBean() {
		filtro = new UsuarioFilter();
		usuariosFiltrados = new HashSet<Usuario>();
	}

	public void pesquisar() {
		usuariosFiltrados = usuarioRepository.filtrados(filtro);
	}

	public Set<Usuario> getUsuariosFiltrados() {
		return usuariosFiltrados;
	}

	public UsuarioFilter getFiltro() {
		return filtro;
	}

}

src/main/webapp/usuarios/PesquisaUsuarios.xhtml
<ui:composition template="/WEB-INF/template/LayoutPadrao.xhtml"
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">    
    
    <!-- xmlns:o="http://omnifaces.org/ui" -->

    <ui:define name="titulo">Pesquisa de Usuários</ui:define>
    
    <ui:define name="corpo">
    
    	<h:form id="frmPesquisa">
    	  <!--  <p:focus context="frmPesquisa"/>  -->     

    	   <h1>Pesquisa de Usuários</h1>
	    	
	    	<p:toolbar style="margin-top: 20px">
	    		<p:toolbarGroup>
	    			<p:commandButton value="Pesquisar" action="#{pesquisaUsuarioBean.pesquisar}" update="@form" /> 
	    		</p:toolbarGroup>
	    		<p:toolbarGroup align="right">
	    			<p:button value="Novo" outcome="/usuarios/Usuarios"
	    			 />
	    		</p:toolbarGroup>
	    	</p:toolbar>	    	
	    	
	    	<p:panelGrid columns="6" id="painel" style="width: 100%; margin-top: 20px"
	    			columnClasses="rotulo, campo">

	    		<p:outputLabel value="Login" for="login" />
	    		<p:inputText id="login" value="#{pesquisaUsuarioBean.filtro.login}" />

	    		<p:outputLabel value="Nome" for="nome" />
	    		<p:inputText id="nome" value="#{pesquisaUsuarioBean.filtro.nome}" />

	    		<p:outputLabel value="E-mail" for="email" />
	    		<p:inputText id="email" value="#{pesquisaUsuarioBean.filtro.email}" />

            </p:panelGrid>
            
	    	<p:dataTable id="usuarioTable" value="#{pesquisaUsuarioBean.usuariosFiltrados}" var="usuario"
		    		style="margin-top: 20px" emptyMessage="Nenhum usuário encontrado."
		    		rows="10" paginator="true" paginatorAlwaysVisible="false" paginatorPosition="bottom">
	    		
	    		<p:column headerText="Código" style="text-align: center; width: 100px">
	    			<h:outputText value="#{usuario.id}"/>
	    		</p:column>

	    		<p:column headerText="Login">
	    			<h:outputText value="#{usuario.login}"/>
	    		</p:column>

	    		<p:column headerText="Nome">
	    			<h:outputText value="#{usuario.nome}"/>
	    		</p:column>	    		

	    		<p:column headerText="E-mail">
	    			<h:outputText value="#{usuario.email}"/>	    			
	    		</p:column>
	    		
	    		<p:column headerText="Ativo">
	    			<h:outputText value="#{usuario.status}"/>	    			
	    		</p:column>

	    		<p:column headerText="Editar" style="text-align: center; width: 50px">
	    			<p:button icon="ui-icon-pencil" title="Editar Usuário" 
	    			       outcome="/usuarios/Usuarios">
	    				<f:param name="usuario" value="#{usuario.id}" />
	    			</p:button>
	    		</p:column>
	    	</p:dataTable>
            
    	</h:form>
    </ui:define>
</ui:composition>

src/main/webapp/usuarios/Usuarios.xhtml
<ui:composition template="/WEB-INF/template/LayoutPadrao.xhtml"
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui"
    xmlns:o="http://omnifaces.org/ui">

	<f:metadata>
		<o:viewParam name="usuario" value="#{cadastroUsuarioBean.usuario}" />
		<f:event listener="#{cadastroUsuarioBean.inicializar}" type="preRenderView" />
	</f:metadata>

    <ui:define name="titulo">#{cadastroUsuarioBean.editando ? "Edição de Usuário" : "Novo Usuário"}</ui:define>
     
    <ui:define name="corpo">
    	<h:form id="frmCadastro">
    	    <p:focus context="frmCadastro"/>
    	   <h1>#{cadastroUsuarioBean.editando ? "Edição de Usuário" : "Novo Usuário"}</h1>	    	
	    	<!-- <p:messages autoUpdate="false" /> -->
	    	<p:messages autoUpdate="true" closable="true" />
	    	
	    	<ui:include src="/WEB-INF/template/usuarios/BotoesUsuarios.xhtml" />
	    	
	    	<ui:include src="/WEB-INF/template/usuarios/CorpoUsuarios.xhtml" />
    	</h:form>
    </ui:define>
</ui:composition>