src/main/java/br/uece/favet/model/Animal.java
package br.uece.favet.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.apache.commons.lang3.StringUtils;

import br.uece.favet.util.jsf.FacesUtil;

@Entity
@Table(name = "animal")
public class Animal implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY, generator = "animal_id_seq")
	@SequenceGenerator(name = "animal_id_seq", sequenceName = "animal_id_seq", allocationSize = 1)
	private Long id;

	// @NotBlank
	@Column(nullable = false, length = 100)
	private String nome;

	@Column(name = "codigo_legado", length = 10)
	private String codigoLegado;// Código do outro sistema

	// @NotNull
	@ManyToOne
	@JoinColumn(name = "proprietario_id", nullable = false, foreignKey = @ForeignKey(name = "fk_animal__proprietario__proprietario_id"))
	private Proprietario proprietario;

	@Temporal(TemporalType.DATE)
	@Column(name = "data_nascimento")
	private Date dataNascimento;

	@Column(length = 1, nullable = false)
	private String sexo;

	// @NotNull
	@ManyToOne
	@JoinColumn(name = "especie_id", nullable = false, foreignKey = @ForeignKey(name = "fk_animal__especie__especie_id"))
	private Especie especie;

	// @NotNull
	@ManyToOne
	@JoinColumn(name = "raca_id", nullable = false, foreignKey = @ForeignKey(name = "fk_animal__raca__raca_id"))
	private Raca raca;

	@Column(name = "raca_sem_cadastro", length = 40)
	private String racaSemCadastro;

	@Column(nullable = true)
	private Double peso;

	@Column(nullable = true)
	private boolean castrado = false;

	@Column(nullable = true)
	private boolean pedigree = false;
	
	@Column(nullable = true)
	private boolean obito = false;

	@Column(columnDefinition = "text")
	private String observacao;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getCodigoLegado() {
		return codigoLegado;
	}

	public void setCodigoLegado(String codigoLegado) {
		this.codigoLegado = codigoLegado;
	}

	public Proprietario getProprietario() {
		return proprietario;
	}

	public void setProprietario(Proprietario proprietario) {
		this.proprietario = proprietario;
	}

	public Date getDataNascimento() {
		return dataNascimento;
	}

	public void setDataNascimento(Date dataNascimento) {
		this.dataNascimento = dataNascimento;
	}

	public String getSexo() {
		return sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	public Especie getEspecie() {
		return especie;
	}

	public void setEspecie(Especie especie) {
		this.especie = especie;
	}

	public Raca getRaca() {
		return raca;
	}

	public void setRaca(Raca raca) {
		this.raca = raca;
	}

	public String getRacaSemCadastro() {
		return racaSemCadastro;
	}

	public void setRacaSemCadastro(String racaSemCadastro) {
		this.racaSemCadastro = racaSemCadastro;
	}

	public Double getPeso() {
		return peso;
	}

	public void setPeso(Double peso) {
		this.peso = peso;
	}

	public boolean isCastrado() {
		return castrado;
	}

	public void setCastrado(boolean castrado) {
		this.castrado = castrado;
	}
	
	public boolean isPedigree() {
		return pedigree;
	}

	public void setPedigree(boolean pedigree) {
		this.pedigree = pedigree;
	}

	public boolean isObito() {
		return obito;
	}

	public void setObito(boolean obito) {
		this.obito = obito;
	}

	public String getObservacao() {
		return observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

	@Transient
	public boolean isAnimalValido() {
		boolean animalValido = true;

		if (this.getNome().isEmpty()) {
			animalValido = false;
			FacesUtil.addErrorMessage("Nome do animal não informado");
		} else {
			/*
			 * if (this.proprietario == null || this.proprietario.getId() ==
			 * null) { animalValido = false;
			 * FacesUtil.addErrorMessage("Proprietário do animal  não informado"
			 * ); } else {
			 */
			if (this.especie == null || this.especie.getId() == null) {
				animalValido = false;
				FacesUtil.addErrorMessage("Espécie do animal não informada");
			} else {
				if (this.raca == null || this.raca.getId() == null) {
					animalValido = false;
					FacesUtil.addErrorMessage("Raça do animal não informada");
				}
			}
		}

		// }

		return animalValido;
	}

	@Transient
	public boolean isEhRacaSemCadastro() {
		return StringUtils.isNotBlank(this.racaSemCadastro);
	}

	@Transient
	public boolean isNovo() {
		return this.getProprietario() == null; 
	}
	
	@Transient	
	public boolean isExistente(){
		return !isNovo();
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + (castrado ? 1231 : 1237);
		result = prime * result
				+ ((codigoLegado == null) ? 0 : codigoLegado.hashCode());
		result = prime * result
				+ ((dataNascimento == null) ? 0 : dataNascimento.hashCode());
		result = prime * result + ((especie == null) ? 0 : especie.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((nome == null) ? 0 : nome.hashCode());
		result = prime * result + (obito ? 1231 : 1237);
		result = prime * result
				+ ((observacao == null) ? 0 : observacao.hashCode());
		result = prime * result + (pedigree ? 1231 : 1237);
		result = prime * result + ((peso == null) ? 0 : peso.hashCode());
		result = prime * result
				+ ((proprietario == null) ? 0 : proprietario.hashCode());
		result = prime * result + ((raca == null) ? 0 : raca.hashCode());
		result = prime * result
				+ ((racaSemCadastro == null) ? 0 : racaSemCadastro.hashCode());
		result = prime * result + ((sexo == null) ? 0 : sexo.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Animal other = (Animal) obj;
		if (castrado != other.castrado)
			return false;
		if (codigoLegado == null) {
			if (other.codigoLegado != null)
				return false;
		} else if (!codigoLegado.equals(other.codigoLegado))
			return false;
		if (dataNascimento == null) {
			if (other.dataNascimento != null)
				return false;
		} else if (!dataNascimento.equals(other.dataNascimento))
			return false;
		if (especie == null) {
			if (other.especie != null)
				return false;
		} else if (!especie.equals(other.especie))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (nome == null) {
			if (other.nome != null)
				return false;
		} else if (!nome.equals(other.nome))
			return false;
		if (obito != other.obito)
			return false;
		if (observacao == null) {
			if (other.observacao != null)
				return false;
		} else if (!observacao.equals(other.observacao))
			return false;
		if (pedigree != other.pedigree)
			return false;
		if (peso == null) {
			if (other.peso != null)
				return false;
		} else if (!peso.equals(other.peso))
			return false;
		if (proprietario == null) {
			if (other.proprietario != null)
				return false;
		} else if (!proprietario.equals(other.proprietario))
			return false;
		if (raca == null) {
			if (other.raca != null)
				return false;
		} else if (!raca.equals(other.raca))
			return false;
		if (racaSemCadastro == null) {
			if (other.racaSemCadastro != null)
				return false;
		} else if (!racaSemCadastro.equals(other.racaSemCadastro))
			return false;
		if (sexo == null) {
			if (other.sexo != null)
				return false;
		} else if (!sexo.equals(other.sexo))
			return false;
		return true;
	}
	
}

src/main/java/br/uece/favet/model/Proprietario.java
package br.uece.favet.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

@Entity
@Table(name="proprietario")
public class Proprietario implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY, generator="proprietario_id_seq")
    @SequenceGenerator(name="proprietario_id_seq", sequenceName="proprietario_id_seq", allocationSize=1)
	private Long id;
	@Column(nullable = false, length = 100)
	private String nome;
	@Column(nullable = false, unique=true, length = 14)	
	private String cpfCnpj;

	@Embedded
	private Endereco endereco;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "data_criacao")
	private Date dataCriacao;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_hora_criacao")
	private Date dataHoraCriacao;
	
	@Column(nullable=true, length = 100)
	private String email;
	@Column(nullable=true, length = 15)
	private String telefone;
	@Column(nullable=true, length = 15)	
	private String celular;
	
	@OneToMany(mappedBy = "proprietario", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.EAGER)	
	private List<Animal> animais  = new ArrayList<>();

	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getNome() {
		return nome;
	}
	public void setNome(String nome) {
		this.nome = nome;
	}
	public String getCpfCnpj() {
		return cpfCnpj;
	}
	public void setCpfCnpj(String cpfCnpj) {
		this.cpfCnpj = cpfCnpj;
	}

	public Endereco getEndereco() {
		return endereco;
	}
	public void setEndereco(Endereco endereco) {
		this.endereco = endereco;
	}

	public Date getDataCriacao() {
		return dataCriacao;
	}
	public void setDataCriacao(Date dataCriacao) {
		this.dataCriacao = dataCriacao;
	}
	
	public Date getDataHoraCriacao() {
		return dataHoraCriacao;
	}
	public void setDataHoraCriacao(Date dataHoraCriacao) {
		this.dataHoraCriacao = dataHoraCriacao;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getTelefone() {
		return telefone;
	}
	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}
	public String getCelular() {
		return celular;
	}
	public void setCelular(String celular) {
		this.celular = celular;
	}
	public List<Animal> getAnimais() {
		return animais;
	}
	public void setAnimais(List<Animal> animais) {
		this.animais = animais;
	}

	@Transient
	public boolean isNovo(){
		return getId() == null;
	}

	@Transient	
	public boolean isExistente(){
		return !isNovo();
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((animais == null) ? 0 : animais.hashCode());
		result = prime * result + ((celular == null) ? 0 : celular.hashCode());
		result = prime * result + ((cpfCnpj == null) ? 0 : cpfCnpj.hashCode());
		result = prime * result
				+ ((dataCriacao == null) ? 0 : dataCriacao.hashCode());
		result = prime * result
				+ ((dataHoraCriacao == null) ? 0 : dataHoraCriacao.hashCode());
		result = prime * result + ((email == null) ? 0 : email.hashCode());
		result = prime * result
				+ ((endereco == null) ? 0 : endereco.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((nome == null) ? 0 : nome.hashCode());
		result = prime * result
				+ ((telefone == null) ? 0 : telefone.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Proprietario other = (Proprietario) obj;
		if (animais == null) {
			if (other.animais != null)
				return false;
		} else if (!animais.equals(other.animais))
			return false;
		if (celular == null) {
			if (other.celular != null)
				return false;
		} else if (!celular.equals(other.celular))
			return false;
		if (cpfCnpj == null) {
			if (other.cpfCnpj != null)
				return false;
		} else if (!cpfCnpj.equals(other.cpfCnpj))
			return false;
		if (dataCriacao == null) {
			if (other.dataCriacao != null)
				return false;
		} else if (!dataCriacao.equals(other.dataCriacao))
			return false;
		if (dataHoraCriacao == null) {
			if (other.dataHoraCriacao != null)
				return false;
		} else if (!dataHoraCriacao.equals(other.dataHoraCriacao))
			return false;
		if (email == null) {
			if (other.email != null)
				return false;
		} else if (!email.equals(other.email))
			return false;
		if (endereco == null) {
			if (other.endereco != null)
				return false;
		} else if (!endereco.equals(other.endereco))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (nome == null) {
			if (other.nome != null)
				return false;
		} else if (!nome.equals(other.nome))
			return false;
		if (telefone == null) {
			if (other.telefone != null)
				return false;
		} else if (!telefone.equals(other.telefone))
			return false;
		return true;
	}

}

src/main/java/br/uece/favet/controller/PesquisaAnimalBean.java
package br.uece.favet.controller;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.faces.bean.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import br.uece.favet.model.Animal;
import br.uece.favet.repository.AnimalRepository;
import br.uece.favet.repository.filter.AnimalFilter;
import br.uece.favet.security.Seguranca;

@Named
@ViewScoped
public class PesquisaAnimalBean implements Serializable {

	private static final long serialVersionUID = 1L;

	@Inject
	private Seguranca seguranca;	
	
	@Inject
	private AnimalRepository animalRepository;

	private AnimalFilter filtro;

	private Set<Animal> animaisFiltrados;

	public PesquisaAnimalBean() {
		filtro = new AnimalFilter();
		animaisFiltrados = new HashSet<Animal>();
	}

	public void pesquisar() {
		animaisFiltrados = animalRepository.filtrados(filtro);
	}

	public Set<Animal> getAnimaisFiltrados() {
		return animaisFiltrados;
	}

	public AnimalFilter getFiltro() {
		return filtro;
	}
	
	public boolean isUsuarioVeterinario() {
		return seguranca.getTipoGrupoUsuario().toUpperCase().equals("VETERINARIO");
	}

}

src/main/webapp/WEB-INF/template/proprietarios/AnimaisProprietarios.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

   <!--  ="#{cadastroProprietarioBean.proprietario.existente}" -->
    <p:commandButton disabled="#{cadastroProprietarioBean.proprietario.novo}" value="Novo animal" style="width: auto" 
							oncomplete="PF('novoAnimalDialog').show()"
							action="#{cadastroProprietarioBean.novoAnimal}"
							process="@this" update="frmCadastro:tabview:novoAnimalDialog">
							<p:resetInput target="frmCadastro:tabview:novoAnimalDialog" />
	</p:commandButton>
   <h:outputText value="Será habilitado após salvar o proprietário." rendered="#{cadastroProprietarioBean.proprietario.novo}" 
         id="avisoBotaoNovoAnimal" style="width: 100%; margin-left: 10px" />

    <div>
    
	<p:dataTable value="#{cadastroProprietarioBean.proprietario.animais}" style="width: 100%; margin-top: 10px" 
	         var="animal" id="tabelaAnimais">

		<p:column headerText="Cod. Proprietario" style="text-align: center; width: 100px" rendered="false">
			<h:outputText value="#{animal.proprietario.id}" id="proprietario_id" />
        </p:column>

		<p:column headerText="Cod. Animal" style="text-align: center; width: 100px">
			<h:outputText value="#{animal.id}" id="id" />
        </p:column>
        					
		<p:column headerText="Nome">
		   <h:outputText value="#{animal.nome}" id="nome"/>
        </p:column>
        
		<p:column headerText="Cod. Legado">
		   <h:outputText value="#{animal.codigoLegado}"/>
        </p:column>
        
		<p:column headerText="Nascimento" style="text-align: center; width: 100px">
		   <h:outputFormat  id="dataNascimento" value="#{animal.dataNascimento}">
		      <f:convertDateTime pattern="dd/MM/yyyy" />
		   </h:outputFormat>
		</p:column>
		 
		<p:column headerText="Sexo">
		   <h:outputText value="#{animal.sexo}"/>
        </p:column>
        
		<p:column headerText="Espécie">
		   <h:outputText value="#{animal.especie.nome}"/>
        </p:column>

		<p:column headerText="Raça">
		   <h:outputText value="#{animal.raca.nome}"/>
        </p:column>
        
		<p:column headerText="Desc. Raça">  
		   <h:outputText value="#{animal.racaSemCadastro}" rendered="#{animal.ehRacaSemCadastro}" />
        </p:column>
        
		<p:column headerText="Peso">
	        <h:outputText value="#{animal.peso}"/> 
        </p:column>
        
		<p:column headerText="Óbito">
		   <h:outputText value="#{animal.obito?'Sim':'Não'}"/>
        </p:column>

   		<p:column headerText="Editar" style="text-align: center; width: 50px">
		    <p:commandButton icon="ui-icon-pencil" 
					oncomplete="PF('novoAnimalDialog').show()"
					action="#{cadastroProprietarioBean.editarAnimal(animal)}"
					process="@this" update="frmCadastro:tabview:novoAnimalDialog">
					<p:resetInput target="frmCadastro:tabview:novoAnimalDialog" />
			</p:commandButton>
   		</p:column>

   		<p:column headerText="Excluir" style="text-align: center; width: 50px">
              <p:commandButton icon="ui-icon-trash" title="Excluir" oncomplete="PF('confirmacaoExclusao').show()"
		    			process="@this" update="frmCadastro:tabview:confirmacaoExclusaoDialog">
	    			<f:setPropertyActionListener target="#{cadastroProprietarioBean.animalSelecionado}" 
	    				value="#{animal}" />
	    			</p:commandButton>
   		</p:column>

   		<p:column headerText="Criar Atendendimento" style="text-align: center; width: 100px"
   		      rendered="#{!cadastroProprietarioBean.usuarioVeterinario}">
   			<p:button icon="ui-icon-suitcase" title="Novo Atendimento"
   			          disabled="#{cadastroProprietarioBean.usuarioVeterinario}" 
   			       outcome="/atendimentospacientes/AtendimentoPacientes">
   				<f:param name="animal" value="#{animal.id}" />
   			</p:button>
   		</p:column>

   		<p:column headerText="Prontuário" style="text-align: center; width: 100px">
				<p:commandButton value="Emitir" action="#{relatorioDadosAnimalBean.emitir(animal.id)}"
					    				ajax="false" />
   		</p:column>


	</p:dataTable>
    </div>
    
	    <p:confirmDialog header="Exclusão de animal" 
    		message="Tem certeza que deseja excluir o animal #{cadastroProprietarioBean.animalSelecionado.nome}?"
    		widgetVar="confirmacaoExclusao"	id="confirmacaoExclusaoDialog">
    		<p:button value="Não" onclick="PF('confirmacaoExclusao').hide(); return false;" />
    		<p:commandButton value="Sim" oncomplete="PF('confirmacaoExclusao').hide();"
    			action="#{cadastroProprietarioBean.excluirAnimal}" process="@this"
    			update="frmCadastro:tabview:tabelaAnimais novoAnimalPanel" />
    	</p:confirmDialog>

       <!-- ####### INICIO DIALOG  DE CRIAÇÃO E EDIÇÃO DE ANIMAIS ####### -->
    	<p:dialog widgetVar="novoAnimalDialog" id="novoAnimalDialog" modal="true"
		header="Novo Animal" resizable="false" responsive="true">

		<h:panelGroup id="novoAnimalPanel" layout="block" >
		   
			<p:panelGrid columns="4" style="width: 100%; margin-top: 20px"
      		columnClasses="rotulo, campo, rotulo, campo">

				<p:outputLabel value="Código" />
					<h:outputText value="#{cadastroProprietarioBean.animalEdicao.id}" id="animal_id" />
		
				<p:outputLabel value="Nome" />
				<p:inputText type="text" id="nomeAnimal" size="30" maxlength="100"
				        value="#{cadastroProprietarioBean.animalEdicao.nome}">
				</p:inputText>
				
		       <p:outputLabel value="Cód. Legado" />
				<p:inputText type="number" id="codLegadoAnimal" size="30" maxlength="10"
				        value="#{cadastroProprietarioBean.animalEdicao.codigoLegado}">
				</p:inputText>

		       <p:outputLabel value="Nascimento" />
  			   <p:calendar id="dataNascimento" value="#{cadastroProprietarioBean.animalEdicao.dataNascimento}" pattern="dd/MM/yyyy">
			   </p:calendar>

		        <p:outputLabel for="sexo" value="sexo:" />
		        <p:selectOneMenu id="sexo" value="#{cadastroProprietarioBean.animalEdicao.sexo}" >
					<f:selectItem itemLabel="Selecione um sexo" />		        
		            <f:selectItem itemLabel="Macho" itemValue="M" />
		            <f:selectItem itemLabel="Fêmea" itemValue="F" />
		        </p:selectOneMenu>

				<p:outputLabel value="Especie" for="especie" />
				<p:selectOneMenu id="especie" value="#{cadastroProprietarioBean.animalEdicao.especie}" rendered="#{cadastroProprietarioBean.cadastrandoAnimal}">
					<f:selectItem itemLabel="Selecione uma espécie" />
 				     <f:selectItems value="#{cadastroProprietarioBean.especies}" var="especie" 
					   itemValue="#{especie}" itemLabel="#{especie.nome}"/>
   				     <p:ajax listener="#{cadastroProprietarioBean.carregarRacasPorEspecie()}" update="raca" />					   
				</p:selectOneMenu>		

				<p:outputLabel value="Raça" for="raca" />
				<p:selectOneMenu id="raca" value="#{cadastroProprietarioBean.animalEdicao.raca}">
					<f:selectItem itemLabel="Selecione uma raça" />
 				     <f:selectItems value="#{cadastroProprietarioBean.racas}" var="raca" 
					   itemValue="#{raca}" itemLabel="#{raca.nome}"/>
				</p:selectOneMenu>
				
		       <p:outputLabel value="Espécie - Raça (Sem Cadastro)" />
				<p:inputText type="text" id="racaSemCadastro" size="30" maxlength="40"
				        value="#{cadastroProprietarioBean.animalEdicao.racaSemCadastro}">
				</p:inputText>				

		 		<p:outputLabel value="Peso" />
				<p:inputText type="number" id="peso"  
				     value="#{cadastroProprietarioBean.animalEdicao.peso}"/>

                  <p:selectBooleanCheckbox itemLabel="Castrado"
								value="#{cadastroProprietarioBean.animalEdicao.castrado}">
				 </p:selectBooleanCheckbox>
 
                   <p:selectBooleanCheckbox itemLabel="Pedigree"
								value="#{cadastroProprietarioBean.animalEdicao.pedigree}">
				 </p:selectBooleanCheckbox>
 
                   <p:selectBooleanCheckbox itemLabel="Óbito"
								value="#{cadastroProprietarioBean.animalEdicao.obito}">
				 </p:selectBooleanCheckbox>
			</p:panelGrid>
			
         
          <div>	    	
	    	<p:tabView id="tabviewAnimal" style="margin-top: 20px">
	    		<p:tab id="tabObservacaoAnimal" title="Observação">
  			        <p:outputLabel value="Observação" />
				    <p:inputTextarea rows="10" style="width: 100%"
				      id="obsercacaoAnimal" value="#{cadastroProprietarioBean.animalEdicao.observacao}" />
	    		</p:tab>
	    		<p:tab id="tabVacinasAnimais" title="Vacinas">
	    		   <h3>Em desenvolvimento</h3>
	    		</p:tab>	    		
	    	</p:tabView>
	     </div>
	     		
	    		<p:commandButton value="Adicionar" process="novoAnimalDialog" rendered="#{cadastroProprietarioBean.animalEdicao.novo}"
	    			update="frmCadastro:tabview:tabelaAnimais novoAnimalPanel"
	    		     oncomplete="if (!args.validationFailed) PF('novoAnimalDialog').hide()"
	    			action="#{cadastroProprietarioBean.adicionarAnimal}"  />
	     		
	    		<p:commandButton value="Alterar" process="novoAnimalDialog" rendered="#{cadastroProprietarioBean.animalEdicao.existente}"
	    			update="frmCadastro:tabview:tabelaAnimais novoAnimalPanel"
	    		     oncomplete="if (!args.validationFailed) PF('novoAnimalDialog').hide()"
	    			action="#{cadastroProprietarioBean.alterarAnimal}"  />
	     		
				<p:commandButton value="Cancelar" onclick="PF('novoAnimalDialog').hide()" />
				
		</h:panelGroup>
		
	</p:dialog>    
	
       <!-- ####### FIM DIALOG  DE CRIAÇÃO E EDIÇÃO DE ANIMAIS ####### -->
       
</ui:composition>

src/main/webapp/WEB-INF/template/proprietarios/ObservacaoProprietarios.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">

	<h:panelGroup layout="block" style="padding-right: 10px">
		<p:inputTextarea rows="10" style="width: 100%"
		      id="obsercacao" value="#{cadastroProprietarioBean.proprietario.observacao}" />
	</h:panelGroup>
  	
</ui:composition>