src/main/java/br/uece/favet/model/AtendimentoPaciente.java
package br.uece.favet.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

import org.apache.commons.lang3.StringUtils;

import br.uece.favet.model.enums.StatusAtendimentoPaciente;
import br.uece.favet.model.enums.TipoAtendimentoPaciente;
import br.uece.favet.util.jsf.FacesUtil;

@Entity
@Table(name="atendimento_paciente")
public class AtendimentoPaciente implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY, generator = "atendimento_paciente_id_seq")
	@SequenceGenerator(name = "atendimento_paciente_id_seq", sequenceName = "atendimento_paciente_id_seq", allocationSize = 1)	
	private Long id;
	
	@Column(length = 10)
	private String senha;
	
	@Column(nullable=true)
	private boolean prioritario = false;

	//@NotNull
	@ManyToOne
	@JoinColumn(name = "usuario_criou_id", foreignKey = @ForeignKey(name = "fk_atendimento_paciente__usuario__usuario_criou_id"))	
	private Usuario usuarioCriou;
	
	@ManyToOne
	@JoinColumn(name = "usuario_iniciou_id", foreignKey = @ForeignKey(name = "fk_atendimento_paciente__usuario__usuario_iniciou_id"))	
	private Usuario usuarioIniciou;

	@ManyToOne
	@JoinColumn(name = "usuario_finalizou_id", foreignKey = @ForeignKey(name = "fk_atendimento_paciente__usuario__usuario_finalizou_id"))	
	private Usuario usuarioFinalizou;	

	@ManyToOne
	@JoinColumn(name = "usuario_atualizou_id", foreignKey = @ForeignKey(name = "fk_atendimento_paciente__usuario__usuario_atualizou_id"))	
	private Usuario usuarioAtualizou;	
	
	@ManyToOne
	@JoinColumn(name = "patologia_id", foreignKey = @ForeignKey(name = "fk_atendimento_paciente__patologia__patologia_id"))	
	private Patologia patologia;	
	
	@Column(name="outra_patologia", length = 100)
	private String outraPatologia;//patologia principal	

	@Column(nullable = true, length = 50)
	private String resumo;//poucas palavras para aparecer no Histórico
	
	@NotNull
	//@ManyToOne(cascade=CascadeType.MERGE)
	@ManyToOne
	@JoinColumn(name = "animal_id", nullable = false, foreignKey = @ForeignKey(name = "fk_atendimento_paciente__animal__animal_id"))	
	private Animal animal;

	@Column(nullable = true)
	private Double peso;
	
	//@NotNull
	@ManyToOne
	@JoinColumn(name = "veterinario_id", nullable=true, foreignKey = @ForeignKey(name = "fk_atendimento_paciente__veterinario__veterinario_id"))	
	private Veterinario veterinario;

	//@NotNull
	@ManyToOne
	@JoinColumn(name = "consultorio_id", nullable=true, foreignKey = @ForeignKey(name = "fk_atendimento_paciente__consultorio__consultorio_id"))	
	private Consultorio consultorio;		

	//@NotNull
	@Temporal(TemporalType.DATE)
	@Column(name = "data_criacao")	
	private Date dataCriacao;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_hora_criacao")	
	private Date dataHoraCriacao;
	
	//@NotNull
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_hora_atualizacao")	
	private Date dataHoraAtualizacao;
	
	//@NotNull
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_hora_inicio")	
	private Date dataHoraInicio;
	
	//@NotNull
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_hora_fim")	
	private Date dataHoraFim;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_hora_cancelamento")	
	private Date dataHoraCancelamento;
	
	@NotNull
	@Enumerated(EnumType.STRING)
	@Column(nullable = false, length = 20)
	private StatusAtendimentoPaciente status = StatusAtendimentoPaciente.ESPERA;
	
	@NotNull
	@Enumerated(EnumType.STRING)
	@Column(name="tipo_atendimento_paciente", nullable = false, length = 20)
	private TipoAtendimentoPaciente tipoAtendimentoPaciente = TipoAtendimentoPaciente.CLINICO;	

	@Column(columnDefinition = "text")
	private String anamnese; 	

	@Column(columnDefinition = "text")
	private String diagnostico;

	@Column(name = "exame_complementar", length=255)
	private String exameComplementar;
	
	@Column(name = "exame_complementar2",columnDefinition = "text")
	private String exameComplementar2;	
	
	@Column(name = "resultado_exame_complementar", length=255)	
	private String resultadoExameComplementar;

	@Column(name = "resultado_exame_complementar2",columnDefinition = "text")
	private String resultadoExameComplementar2;	
	
	@Column(columnDefinition = "text")
	private String tratamento;	
	
	@Column(name = "tratamento_cirurgico",columnDefinition = "text")
	private String tratamentoCirurgico;	
	
	@Column(name = "exame_fisico", columnDefinition = "text")
	private String exameFisico;	

	@Column(columnDefinition = "text")
	private String receituario;
	
	@Column(columnDefinition = "text")
	private String observacao;
	
	@Column(name = "laudo_ultrassom", columnDefinition = "text")
	private String laudoUltrassom; 		

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getSenha() {
		return senha;
	}
	
	public boolean isPrioritario() {
		return prioritario;
	}

	public void setPrioritario(boolean prioritario) {
		this.prioritario = prioritario;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	public Usuario getUsuarioCriou() {
		return usuarioCriou;
	}

	public void setUsuarioCriou(Usuario usuarioCriou) {
		this.usuarioCriou = usuarioCriou;
	}

	public Usuario getUsuarioIniciou() {
		return usuarioIniciou;
	}

	public void setUsuarioIniciou(Usuario usuarioIniciou) {
		this.usuarioIniciou = usuarioIniciou;
	}

	public Usuario getUsuarioFinalizou() {
		return usuarioFinalizou;
	}

	public void setUsuarioFinalizou(Usuario usuarioFinalizou) {
		this.usuarioFinalizou = usuarioFinalizou;
	}

	public Usuario getUsuarioAtualizou() {
		return usuarioAtualizou;
	}

	public void setUsuarioAtualizou(Usuario usuarioAtualizou) {
		this.usuarioAtualizou = usuarioAtualizou;
	}

	public Patologia getPatologia() {
		return patologia;
	}

	public void setPatologia(Patologia patologia) {
		this.patologia = patologia;
	}

	public String getOutraPatologia() {
		return outraPatologia;
	}

	public void setOutraPatologia(String outraPatologia) {
		this.outraPatologia = outraPatologia;
	}

	public String getResumo() {
		return resumo;
	}

	public void setResumo(String resumo) {
		this.resumo = resumo;
	}

	public Animal getAnimal() {
		return animal;
	}

	public void setAnimal(Animal animal) {
		this.animal = animal;
	}

	public Double getPeso() {
		return peso;
	}

	public void setPeso(Double peso) {
		this.peso = peso;
	}

	public Veterinario getVeterinario() {
		return veterinario;
	}

	public void setVeterinario(Veterinario veterinario) {
		this.veterinario = veterinario;
	}

	public Consultorio getConsultorio() {
		return consultorio;
	}

	public void setConsultorio(Consultorio consultorio) {
		this.consultorio = consultorio;
	}

	public Date getDataCriacao() {
		return dataCriacao;
	}

	public void setDataCriacao(Date dataCriacao) {
		this.dataCriacao = dataCriacao;
	}

	public Date getDataHoraCriacao() {
		return dataHoraCriacao;
	}

	public void setDataHoraCriacao(Date dataHoraCriacao) {
		this.dataHoraCriacao = dataHoraCriacao;
	}

	public Date getDataHoraAtualizacao() {
		return dataHoraAtualizacao;
	}

	public void setDataHoraAtualizacao(Date dataHoraAtualizacao) {
		this.dataHoraAtualizacao = dataHoraAtualizacao;
	}

	public Date getDataHoraInicio() {
		return dataHoraInicio;
	}

	public void setDataHoraInicio(Date dataHoraInicio) {
		this.dataHoraInicio = dataHoraInicio;
	}

	public Date getDataHoraFim() {
		return dataHoraFim;
	}

	public void setDataHoraFim(Date dataHoraFim) {
		this.dataHoraFim = dataHoraFim;
	}
	
	public Date getDataHoraCancelamento() {
		return dataHoraCancelamento;
	}

	public void setDataHoraCancelamento(Date dataHoraCancelamento) {
		this.dataHoraCancelamento = dataHoraCancelamento;
	}

	public StatusAtendimentoPaciente getStatus() {
		return status;
	}

	public void setStatus(StatusAtendimentoPaciente status) {
		this.status = status;
	}

	public TipoAtendimentoPaciente getTipoAtendimentoPaciente() {
		return tipoAtendimentoPaciente;
	}

	public void setTipoAtendimentoPaciente(
			TipoAtendimentoPaciente tipoAtendimentoPaciente) {
		this.tipoAtendimentoPaciente = tipoAtendimentoPaciente;
	}

	public String getAnamnese() {
		return anamnese;
	}

	public void setAnamnese(String anamnese) {
		this.anamnese = anamnese;
	}

	public String getDiagnostico() {
		return diagnostico;
	}

	public void setDiagnostico(String diagnostico) {
		this.diagnostico = diagnostico;
	}
	
	public String getExameComplementar() {
		return exameComplementar;
	}

	public void setExameComplementar(String exameComplementar) {
		this.exameComplementar = exameComplementar;
	}

	public String getExameComplementar2() {
		return exameComplementar2;
	}

	public void setExameComplementar2(String exameComplementar2) {
		this.exameComplementar2 = exameComplementar2;
	}
	
	public String getResultadoExameComplementar() {
		return resultadoExameComplementar;
	}

	public void setResultadoExameComplementar(String resultadoExameComplementar) {
		this.resultadoExameComplementar = resultadoExameComplementar;
	}
	
	public String getResultadoExameComplementar2() {
		return resultadoExameComplementar2;
	}

	public void setResultadoExameComplementar2(String resultadoExameComplementar2) {
		this.resultadoExameComplementar2 = resultadoExameComplementar2;
	}

	public String getTratamento() {
		return tratamento;
	}

	public void setTratamento(String tratamento) {
		this.tratamento = tratamento;
	}

src/main/java/br/uece/favet/controller/PesquisaAtendimentoPacienteBean.java
package br.uece.favet.controller;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import br.uece.favet.model.AtendimentoPaciente;
import br.uece.favet.model.enums.StatusAtendimentoPaciente;
import br.uece.favet.model.enums.TipoAtendimentoPaciente;
import br.uece.favet.repository.AtendimentoPacienteRepository;
import br.uece.favet.repository.filter.AtendimentoPacienteFilter;
import br.uece.favet.security.Seguranca;

@Named
@ViewScoped
public class PesquisaAtendimentoPacienteBean implements Serializable {

	private static final long serialVersionUID = 1L;

	@Inject
	private AtendimentoPacienteRepository atendimentoPacienteRepository;
	
	@Inject
	private Seguranca seguranca;	

	private AtendimentoPacienteFilter filtro;

	private List<AtendimentoPaciente> atendimentosFiltrados;
	
	private String totaisAtendimentos;
	private int totalEmEspera = 0;
	private int totalEmAtendimento = 0;
	private int totalAtendido = 0;
	private int totalCancelado = 0;

	public PesquisaAtendimentoPacienteBean() {
		filtro = new AtendimentoPacienteFilter();
		atendimentosFiltrados = new ArrayList<>();
		//createHorizontalBarModel();
	}
	
	public String getTotaisAtendimentos() {
		return totaisAtendimentos;
	}

	public void pesquisar() {
		atendimentosFiltrados = atendimentoPacienteRepository.filtrados(filtro);
		carregarTotaisAtendimentos();
	}
	
	private String pegaParametro(){
		String tipoAtendimento = null;
		
		try {
			tipoAtendimento = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap().get("tipoatendimento");			
		} catch (Exception e) {
			
		}

		if (tipoAtendimento == null){
			tipoAtendimento = "todos";
		}
		
		System.out.println("tipoAtendimento: "+tipoAtendimento);		
		
		return tipoAtendimento;
	}
	
	public void pesquisarEmEspera() {
		
		String paramTipoAtendimento = pegaParametro();
		switch (paramTipoAtendimento) {
 		case "clinico":
 			TipoAtendimentoPaciente tipoAtendimentosClinico[] = {TipoAtendimentoPaciente.CLINICO, TipoAtendimentoPaciente.RETORNO}; 			
 			filtro.setTiposAtendimentos(tipoAtendimentosClinico);
			break;
		case "cirurgico":
 			TipoAtendimentoPaciente tipoAtendimentoCirurgico[] = {TipoAtendimentoPaciente.CIRURGICO, TipoAtendimentoPaciente.AVALIACAO_CIRURGICA, TipoAtendimentoPaciente.RETORNO_CIRURGICO}; 			
 			filtro.setTiposAtendimentos(tipoAtendimentoCirurgico); 			
			break;
		case "ultrassom":
 			TipoAtendimentoPaciente tipoAtendimentoUltrassom[] = {TipoAtendimentoPaciente.EXAME}; 			
 			filtro.setTiposAtendimentos(tipoAtendimentoUltrassom); 			
			break;			
		default:
			break;
		}
		
		filtro.setDataAtendimentoDe(new Date());
		filtro.setDataAtendimentoAte(new Date());
		
		atendimentosFiltrados = atendimentoPacienteRepository.filtradosEmEspera(filtro);
	}
	
	public StatusAtendimentoPaciente[] getStatuses() {
		return StatusAtendimentoPaciente.values();
	}

	public TipoAtendimentoPaciente[] getTiposAtendimentos() {
		return TipoAtendimentoPaciente.values();
	}	
	
	public List<AtendimentoPaciente> getAtendimentosFiltrados() {
		return atendimentosFiltrados;
	}

	public AtendimentoPacienteFilter getFiltro() {
		return filtro;
	}
	
	private void carregarTotaisAtendimentos(){

		totalEmEspera = 0;
		totalEmAtendimento = 0;
		totalAtendido = 0;
		totalCancelado = 0;
		
		for (AtendimentoPaciente atendimento : this.atendimentosFiltrados) {

			if (atendimento.getStatus().toString().equals(StatusAtendimentoPaciente.ESPERA.toString())){
				totalEmEspera = totalEmEspera + 1;
			} else if (atendimento.getStatus().toString().equals(StatusAtendimentoPaciente.ATENDIMENTO.toString())){
				totalEmAtendimento++;
			} else if (atendimento.getStatus().toString().equals(StatusAtendimentoPaciente.ATENDIDO.toString())){
				totalAtendido++;				
			} else if (atendimento.getStatus().toString().equals(StatusAtendimentoPaciente.CANCELADO.toString())){
				totalCancelado++;
			}
		}
		
		this.totaisAtendimentos = "Em Espera: "+String.valueOf(totalEmEspera)+"     |"+
				                  "Em Atendimento: "+String.valueOf(totalEmAtendimento)+"      |"+
				                  "Atendido(s): "+String.valueOf(totalAtendido)+"     |"+
				                  "Cancelado(s): "+String.valueOf(totalCancelado);

	}

	public int getTotalEmEspera() {
		return totalEmEspera;
	}

	public int getTotalEmAtendimento() {
		return totalEmAtendimento;
	}

	public int getTotalAtendido() {
		return totalAtendido;
	}

	public int getTotalCancelado() {
		return totalCancelado;
	}
	
	public boolean isUsuarioVeterinario() {
		return seguranca.getTipoGrupoUsuario().toUpperCase().equals("VETERINARIO");
	}
	
	public boolean isUsuarioVeterinarioCirurgiao(){
		if (isUsuarioVeterinario()){
			return seguranca.getVeterinarioUsuario().isCirurgiao();
		} 
		return false;
	}	
	
	public boolean isUsuarioVeterinarioClinico(){
		if (isUsuarioVeterinario()){
			return seguranca.getVeterinarioUsuario().getClinico();
		} 
		return false;
	}	
	
	public boolean isUsuarioVeterinarioLaudista(){
		if (isUsuarioVeterinario()){
			return seguranca.getVeterinarioUsuario().getFazExames();
		} 
		return false;
	}	
	
	
	public boolean usuarioPodeAtenderTipoCirurgico(boolean isTipoAtendimentoCirurgico){
		
		if (!isTipoAtendimentoCirurgico){
			return true;
		}else { //é Tipo Atendimento Cirúrgico
			if (!isUsuarioVeterinario()){
				return true;
			} else { //usuário é Veterinário
			    if (isUsuarioVeterinarioCirurgiao()){
					return true;
				} else {
				    return false;			
				}				
			}

		}
	}
	
	public boolean usuarioPodeAtender2(TipoAtendimentoPaciente tipoAtendimento){
		
		if (!isUsuarioVeterinario()){ //não é Veterinário, tem acesso a tudo 
			return true;
		} 
		else if (tipoAtendimento == TipoAtendimentoPaciente.CIRURGICO ||
				tipoAtendimento == TipoAtendimentoPaciente.EXAME){
			if (isUsuarioVeterinarioCirurgiao() || isUsuarioVeterinarioLaudista()){
				return true;
			} else { //É veterinário Clínico
				return false;
			}
					
		} else { //Tipo de Atendimento Clínico ou Exame
			return true;
		}
			
	}

	public boolean usuarioPodeAtender(TipoAtendimentoPaciente tipoAtendimento){
		
		if (!isUsuarioVeterinario()){ //não é Veterinário, tem acesso a tudo 
			return true;
		} 
		else{
			if ((tipoAtendimento == TipoAtendimentoPaciente.CLINICO || tipoAtendimento == TipoAtendimentoPaciente.RETORNO)
				 && isUsuarioVeterinarioClinico()){
				return true;
			} else if ((tipoAtendimento == TipoAtendimentoPaciente.CIRURGICO ||
					    tipoAtendimento == TipoAtendimentoPaciente.AVALIACAO_CIRURGICA ||
					    tipoAtendimento == TipoAtendimentoPaciente.RETORNO_CIRURGICO) && isUsuarioVeterinarioCirurgiao() ){
			  return true;
			} else if (tipoAtendimento == TipoAtendimentoPaciente.EXAME && isUsuarioVeterinarioLaudista()){
				return true;
			} else {
				return false;
			}
		}
			
	}
	
	
	public boolean usuarioNaoPodeAtender(TipoAtendimentoPaciente tipoAtendimento){
		return !usuarioPodeAtender(tipoAtendimento);
	}

}

src/main/webapp/atendimentospacientes/PesquisaListaEspera.xhtml
<ui:composition template="/WEB-INF/template/LayoutPadrao.xhtml"
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">    
    
    <!-- xmlns:o="http://omnifaces.org/ui" -->
    
	<f:metadata>
		<f:event listener="#{pesquisaAtendimentoPacienteBean.pesquisarEmEspera}" type="preRenderView" />
	</f:metadata>    

    <ui:define name="titulo">"Pesquisa Atendimentos de Pacientes"</ui:define>
    
    <ui:define name="corpo">
    
    	<h:form id="frmPesquisa">

    	   <h1>Pesquisa Atendimentos de Pacientes</h1>

	    	<p:toolbar style="margin-top: 20px">
	    		<p:toolbarGroup>
	    			<p:commandButton value="Pesquisar" action="#{pesquisaAtendimentoPacienteBean.pesquisarEmEspera}" update="@form" /> 
	    		</p:toolbarGroup>
	    		<p:toolbarGroup align="right">
	    		</p:toolbarGroup>
	    	</p:toolbar>	    	
	    	
	    	<p:panelGrid columns="2" id="painel" style="width: 100%; margin-top: 20px"
	    			columnClasses="rotulo, campo">

      		<p:outputLabel value="Data de Criação" />
	    		<h:panelGroup>
	    			<p:calendar size="10" pattern="dd/MM/yyyy" readonly="true"
	    				value="#{pesquisaAtendimentoPacienteBean.filtro.dataAtendimentoDe}" />
	    			a
	    			<p:calendar size="10" pattern="dd/MM/yyyy" readonly="true"
	    				value="#{pesquisaAtendimentoPacienteBean.filtro.dataAtendimentoAte}" />
	    		</h:panelGroup>

	    		<p:outputLabel value="Status" />
	    		<p:selectOneRadio value="#{pesquisaAtendimentoPacienteBean.filtro.statusEmEspera}">
	    		    <f:selectItem itemLabel="Em Espera" itemValue="ESPERA" />
	    		</p:selectOneRadio>
	    		
	    		<p:outputLabel value="Tipo Atendimento" />
	    		<p:selectManyCheckbox disabled="true" 
	    		        value="#{pesquisaAtendimentoPacienteBean.filtro.tiposAtendimentos}">
	    			<f:selectItems value="#{pesquisaAtendimentoPacienteBean.tiposAtendimentos}" var="tipoAtendimento"
	    				itemValue="#{tipoAtendimento}" itemLabel="#{tipoAtendimento.descricao}" />
	    		</p:selectManyCheckbox>
            </p:panelGrid>
            
	    	<p:dataTable id="atendimentoTable" value="#{pesquisaAtendimentoPacienteBean.atendimentosFiltrados}" var="atendimento"
		    		style="margin-top: 20px" emptyMessage="Nenhum atendimento encontrado."
		    		rows="20" paginator="true" paginatorAlwaysVisible="false" paginatorPosition="bottom">
		    
				<p:column headerText="Data Criação" style="text-align: center; width: 80px">
				   <h:outputFormat  id="data" value="#{atendimento.dataHoraCriacao}">
				      <f:convertDateTime pattern="dd/MM/yyyy HH:mm" />
				   </h:outputFormat>
				</p:column>

	    		<p:column headerText="Atend." style="text-align: center; width: 30px">
	    			<h:outputText value="#{atendimento.id}"/>
	    		</p:column>

	    		<p:column headerText="Senha" style="text-align: center; width: 40px">
	    			<h:outputText value="#{atendimento.senha}"/>
	    		</p:column>

	    		<p:column headerText="Prioritário" style="text-align: center; width: 60px">
	    			<h:outputText value="#{atendimento.nomePrioritario}" />
	    		</p:column>
<!--
	    		<p:column headerText="Resumo" style="text-align: center; width: 100px">
	    			<h:outputText value="#{atendimento.resumo}"/>
	    		</p:column>
-->
	    		<p:column headerText="Status" style="text-align: center; width: 70px">
	    			<h:outputText value="#{atendimento.status.descricao}"/>
	    		</p:column>	    		

	    		<p:column headerText="Tipo" style="text-align: center; width: 50px">
	    			<h:outputText value="#{atendimento.tipoAtendimentoPaciente.descricao}"/>
	    		</p:column>
	    		
	    		<p:column headerText="Veterinário" style="text-align: center; width: 80px">
	    			<h:outputText value="#{atendimento.veterinario.nome}"/>
	    		</p:column>
	    		
	    		<p:column headerText="Consultório" style="text-align: center; width: 80px">
	    			<h:outputText value="#{atendimento.consultorio.nome}"/>
	    		</p:column>
	    		
	    		<p:column headerText="Cod. Animal" style="text-align: center; width: 40px">
	    			<h:outputText value="#{atendimento.animal.id}"/>	    			
	    		</p:column>
	    		
	    		<p:column headerText="Cod. Legado Animal" style="text-align: center; width: 50px">
	    			<h:outputText value="#{atendimento.animal.codigoLegado}"/>	    			
	    		</p:column>	    		

	    		<p:column headerText="Animal" style="text-align: center; width: 50px">
	    			<h:outputText value="#{atendimento.animal.nome}"/>
	    		</p:column>

	    		<p:column headerText="Proprietário" style="text-align: center; width: 80px">
	    			<h:outputText value="#{atendimento.animal.proprietario.nome}"/>
	    		</p:column>	    		
	    		
	    		<p:column headerText="Espécie" style="text-align: center; width: 70px">
	    			<h:outputText value="#{atendimento.animal.especie.nome}"/>
	    		</p:column>

<!-- 
	    		<p:column headerText="Raça" style="text-align: center; width: 70px">
	    			<h:outputText value="#{atendimento.animal.raca.nome}"/>
	    		</p:column>
 -->
	    		<p:column headerText="Editar" style="text-align: center; width: 50px">
	    			<p:button icon="ui-icon-pencil" title="Editar Atendimento"
    			 	       disabled="#{pesquisaAtendimentoPacienteBean.usuarioNaoPodeAtender(atendimento.tipoAtendimentoPaciente)}"	    			
	    			       outcome="/atendimentospacientes/AtendimentoPacientes">
	    				<f:param name="atendimentoPaciente" value="#{atendimento.id}" />
	    			</p:button>
	    		</p:column>

	    		<p:column headerText="Atender" style="text-align: center; width: 70px">
	    		    <p:outputLabel value="vide Tipo de Atendimento"
 						rendered="#{pesquisaAtendimentoPacienteBean.usuarioNaoPodeAtender(atendimento.tipoAtendimentoPaciente)}" >
 					</p:outputLabel>	    		
	    			<p:button icon="ui-icon-suitcase" title="Atender"
  	    		           rendered="#{pesquisaAtendimentoPacienteBean.usuarioPodeAtender(atendimento.tipoAtendimentoPaciente)}"
	    			       outcome="/atendimentospacientes/AtendimentoPacientes">
	    				    <f:param name="atendimentoPaciente" value="#{atendimento.id}" /> 
	    			</p:button>
	    		</p:column>

	    	</p:dataTable>
	    	
    	</h:form>
    </ui:define>
</ui:composition>